config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :events do
    get 'book', to: "events#book"
  end
  resources :attendances, only: [:destroy] do
    collection do
      get 'dashboard', to: "attendances#dashboard"
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :category, presence: true
  validates :location, presence: true
  validates :city, presence: true
  validates :event_time, presence: true
  validates :description, presence: true


  mount_uploader :photo, PhotoUploader
  belongs_to :user

  has_many :attendances
  has_many :attenders, through: :attendances, source: :user

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :events, dependent: :destroy


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_location, :unless => :devise_controller?
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description])
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end


  def store_location
  # store last url - this is needed for post-login redirect to whatever the user last visited.
    return unless request.get?
      if (request.path != "/users/sign_in" &&
          request.path != "/users/sign_up" &&
          request.path != "/users/sign_out" &&
          request.path != "/users/auth/facebook" &&
          request.path != "/users/auth/facebook/callback" &&
        !request.xhr?) # don't store ajax calls
      session[:previous_url] = request.fullpath
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def dashboard
    @myattendances = Attendance.where(user_id: current_user.id)
    @user = current_user
  end

  def destroy
      @attendance = Attendance.find(params[:id])
      @attendance.destroy
      redirect_to dashboard_attendances_path
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only:[:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :book]

  def index
    # @category = params[:event][:category]
    # @events = Event.where(category: @category)
    # @myevents = Attendance.where(user_id: current_user.id).map{ |attendance| attendance.event }

    # @category = params[:event][:category]
    if params[:event].nil? || params[:event][:category].nil? || (params[:event][:category] == "" && params[:event][:city].blank?)
      @events = Event.all
    else
      @category = params[:event][:category]
      @city = params[:event][:city]
      unless @city.blank?
        if @category == ""
          @events = Event.where(city: @city)
        else
          @events = Event.where(category: @category, city: @city)
        end
      else
        @events = Event.where(category: @category)
      end
      # @myevents = Attendance.where(user_id: current_user.id).map{ |attendance| attendance.event }
    end


    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      if event.latitude
        marker.lat event.latitude
        marker.lng event.longitude
      else
        marker.lat '29.978'
        marker.lng '31.1320'
        # CHANGE!
      end
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end

    # @events = Event.all
    # if current_user
    # @myevents = Attendance.where(user_id: current_user.id).map{ |attendance| attendance.event }
    # end

  end

  def show
    @alert_message = "You are viewing #{@event.name}"
    @event_coordinates = { lat: @event.latitude, lng: @event.longitude }

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    @event.save
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  def book
    @event = Event.find(params[:event_id])
    @user = current_user

    if Attendance.exists?(user_id: @user.id, event_id: @event.id)
      redirect_to event_path(@event)
      flash[:alert] = "You have already booked"
       else Attendance.create(user_id: @user.id, event_id: @event.id)
    redirect_to event_path(@event)
    flash[:notice] = "You have successfully booked this event"
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :event_time, :description, :category, :location, :city, :user_id, :photo, :photo_cache)
  end

  def require_login
    if !current_user
       flash[:alert] = "You need to log-in to do this action"
      redirect_to new_user_session_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.new
    @event = Event.new
    @categories = Event.all.map {|event| event.category}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 text-center">

      <div class="profile-dash">

        <% if user_signed_in? && current_user.facebook_picture_url %>
            <% photo_url = current_user.facebook_picture_url.split("?")[0] + "?type=large" %>
            <img src="<%= photo_url %>" alt="" class="avatar-large avatar-dash" style="width: 200px;">
        <% else %>

          <img src="http://style.anu.edu.au/_anu/4/images/placeholders/person.png" alt="" class="avatar-large avatar-dash" style="width: 200px;">

               <% end %>

        <p> <%= current_user.first_name %> <%= current_user.last_name  %> </p>

        <% if current_user.description.nil? %>
          <p>You don't have any description yet. Tell us more about yourself!</p>
          <%= link_to "Edit your profile",  edit_user_registration_path(current_user) %>
        <% else %>
          <p> <%= current_user.description %> </p>
        <% end %>
      </div>

      <h4>As a guest</h4>
        <% if @myattendances.empty? %>
          <p>You are not attending any events</p>
      <!--     todo : put a button to attend an event -->
      <% else %>
          <% @myattendances.each do |attendance| %>
            <h5> <%= link_to attendance.event.name, event_path(attendance.event) %> </h5>
            <p style="font-weight: lighter"><%= link_to "Unbook this event", attendance_path(attendance), method: :delete, data: {confirm: "are you sure ?"} %></p>
          <% end %>
        <% end %>
      <br>

      <hr>

      <h4>As a host</h4>
        <% if @user.events.empty? %>
        <p>You're not hosting any events</p>
        <% else %>
          <% @user.events.each do |event| %>
          <div >
          <%= link_to event.name, event_path(event) %>
          <p style="font-weight: lighter"><%= link_to "Edit this event", edit_event_path(event) %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container" style="margin-bottom: 30px;">
  <h2 class="text-center">Edit your event</h2>
  <div class="row">
    <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>
      <%= simple_form_for(@event) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :event_time, required: true, autofocus: true %>
          <%= f.input :description, required: true, autofocus: true %>
          <%= f.input :category, required: true, autofocus: true %>
          <%= f.input :location, required: true, autofocus: true %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <p>*Be nice with the css, add an horizontal picture*</p>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Save changes", class: "navbar-wagon-item navbar-wagon-button btn" %>
        </div>
        <div>
          <p></br></p>
        </div>
        <%= link_to "Delete the event", event_path(@event), method: :delete %> |
        <%= link_to "Go back", event_path(@event) %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="wrapper">
  <h2>What are you up to?</h2>

<div class="wrapper-map">
          <div id="map" style="width: 100%; height: 320px;"></div>

          <% content_for(:after_js) do %>
            <%= javascript_tag do %>
              $(document).ready(function() {
                var handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' } }, function() {
                  markers = handler.addMarkers(<%= raw @hash.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                  if (markers.length == 0) {
                    handler.getMap().setZoom(2);
                  } else if (markers.length == 1) {
                    handler.getMap().setZoom(14);
                  }
                });
              });

            <% end %>
          <% end %>
      </div>


      <div class="products">

          <% unless @events.nil? %>
            <ul class="list-unstyled list-inline">
              <% @events.each do |event| %>
                <div class="product">
                <!-- default photo or added photo -->
                    <li><div class="photo">
                    <% if event.photo? %>
                    <%= cl_image_tag event.photo, class: "product-image hidden-xs" %>
                    <% else %>
                    <%= image_tag(('https://images.unsplash.com/photo-1478812954026-9c750f0e89fc?dpr=2&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=&bg='), class: "product-image hidden-xs") %>
        <!--             <img src ='https://unsplash.com/photos/anV_zgNDZhc' alt="default-image" class="product-image hidden-xs"> -->
                    <% end %>
                    </div></li>
      <!--             <img src="kudoz.jpg" alt="kudoz" class="product-image hidden-xs"> -->
                <li><div class='product-body'>
                  <h3> <%= link_to event.name, event_path(event) %> </h3>
                  <p><%= event.description %></p>
                </div></li>

<!--                 <li><div class="icons">
                <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
                  <li><a href=""><i class="fa fa-heart"></i></a></li>
                  <li><a href=""><i class="fa fa-share"></i></a></li>
                  <li><a href=""><i class="fa fa-star"></i></a></li>
                </ul>
                </div> -->
<!--                 </li> -->
              </div>

              <% end %>
              </ul>
          <% end %>
      </div>


</div>
<!-- display: inline-block -->

app/views/events/new.html.erb
<div class="container" style="margin-bottom: 30px;">
  <h2 class="text-center">Create a new event</h2>
  <div class="row">
    <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>
      <%= simple_form_for(@event) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :name, required: true, autofocus: true %>
          <%= f.input :event_time, required: true, autofocus: true %>
          <%= f.input :description, required: true, autofocus: true %>
          <%= f.input :category, required: true, autofocus: true %>
          <%= f.input :location, required: true, autofocus: true %>
          <%= f.input :city, required: true, autofocus: true %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <p>*Be nice with the css, add an horizontal picture*</p>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>


        <div class="form-actions">
          <%= f.button :submit, "Create event", class: "navbar-wagon-item navbar-wagon-button btn"  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% if @event.photo? %>
  <div class="banner-event" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.5) 50%), url('<%= cl_image_path @event.photo %>')">
<% else %>
  <div class="banner-event" style="background-image: linear-gradient(135deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.5) 50%), url('https://images.unsplash.com/photo-1478812954026-9c750f0e89fc?dpr=1&auto=format&fit=crop&w=1500&h=1000&q=80&cs=tinysrgb&crop=&bg=')">
<% end %>
    <div class="banner-event-text">
      <h1><%= @event.name %></h1>
      <%= link_to "Attend this event", event_book_path(@event), class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>

      </div>
    </div>
  </div>
</div>



<div class="container" style="padding: 50px 0;">
  <div class="row">
    <div class="col-md-3">
      <div>
        <h4>People attending this event</h4>
        <ul class="list-unstyled">
          <% @event.attenders.each do |user| %>
          <li><%= user.first_name %></li>
        <% end %>
        </ul>
      </div>
    </div>

    <div class="col-md-6">
      <br>
      <p><i class="fa fa-calendar" aria-hidden="true"></i> <%= @event.event_time %> </p>
      <hr>
      <p><i class="fa fa-map-marker lg" aria-hidden="true"></i> <%= @event.location %> <span style="float:right"><%= @event.city %> </span> </p>
      <hr>
      <p><i class="fa fa-list" aria-hidden="true"></i> <%= @event.category %> </p>
      <hr>
      <p><i class="fa fa-user" aria-hidden="true"></i> <%= @event.user.first_name %> </p>
      <hr>
      <p><span class="event-category">Description:</span> <%= @event.description %>
      <p><br></p>
      <%= link_to "Attend this event", event_book_path(@event), class: "navbar-wagon-item navbar-wagon-button btn attend-button" %>

      <p></br></p>

      <div class="col-md-3">
      </div>

    </div>
  </div>
  <%= link_to "Go back", events_path %>
</div>




<!-- <div class="container" style="padding: 50px 0;">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p><span class="event-category">Time:</span> <%= @event.event_time %> </p>
      <hr>
      <p><span class="event-category">Location:</span> <%= @event.location %> </p>
      <hr>
      <p><span class="event-category">Category:</span> <%= @event.category %> </p>
      <hr>
      <p><span class="event-category">Host:</span> <%= @event.user.first_name %> </p>
      <p><span class="event-category">Description:</span> <%#= @event.description %></p>
      <%#= link_to "Attend this event", event_book_path(@event), class: "navbar-wagon-item navbar-wagon-button btn" %>
      <div>
          <p></br></p>
      </div>
      <%#= link_to "Go back", events_path %>
    </div>
  </div>
</div> -->



<%# content_for(:after_js) do %>
  <%#= javascript_tag do %>
<!--     $(document).ready(function() {
      var coord = <%#= raw @flat_coordinates.to_json %>;
      alert('Flat coordinates are ' + coord.lat + ', ' + coord.lng);
    }); -->
  <%# end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Eventify</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>

    <!--
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    -->

    <%= yield %>

    <%= render "shared/footer" %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>

    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag "application" %>
  <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<!--
<% if user_signed_in? %>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log In", new_user_session_path %>
<% end %>
-->

 <div class="banner container-hp">

<!--   <div class="banner-text text-center">
    <h1>Pages#home</h1>
    <p>Find me in app/views/pages/home.html.erb</p>
  </div> -->

  <!-- <div class="banner-text" style="height:75%";> -->
  <div class="banner-text text-center">
    <h1>Networking</h1>
    <p>made easy</p>
  </div>

    <div class="row">
      <div class='col-xs-12 col-sm-10 col-sm-offset-1 col-md-6 col-md-offset-3'>
        <!--
        <form action="" class="form-inline search-bar">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Where are you">
          </div>

          <div class="form-group">
            <input type="dropdown-toggle" class="form-control" placeholder="Category">
          </div>


          <button class="btn btn-success">Search</button>
        </form>
        -->

        <div class="search-bar">
          <%= simple_form_for @event, html: { class: "form-inline" }, method: :get do |f| %>
           <%= f.input :city, placeholder: "city", label: false %>
            <%= f.input :category, placeholder: "Category", collection: @categories, include_blank: "See all categories", label: false %>
            <%= f.button :submit, 'Search', class: "btn btn-success" %>
          <% end %>
        </div>

      </div>
    </div>

</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info fade in">
    <!-- <button class="close" data-dismiss="alert">×</button> -->
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <!--
    <%= flash[:notice] %>
    -->
    <%= notice %>
  </div>
<% end %>


<% if flash[:alert] %>
  <div class="flash flash-info fade in">
   <!--  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    <!-- <button class="close" data-dismiss="alert">×</button> -->
    <!--
    <%= flash[:alert] %>
    -->
    <%= alert %>

  </div>
<% end %>

app/views/shared/_footer.html.erb
 <!-- Footer code -->
<div id="footer">
  <ul class="unstyled list-inline">
    <li class="list-inline-item">
        <i class="fa fa-lightbulb-o" aria-hidden="true"></i> </li>
     <li class="list-inline-item"> <p>All right reserved     |    © Eventify 2023 </p>
    </li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" style="width: 150px;">
    <img src="https://eventify.it/assets/eventify_logo_beta-babf07c00f13850d2d2f0b6bc40377d6.png" />
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Button (call-to-action) -->
    <div style="margin: 0 20px 0 0;">
      <%= link_to "Create an event", new_event_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    </div>
    <!-- Text link -->
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link"><i class="fa fa-question-circle fa-lg" aria-hidden="true"></i>
    </a> -->

    <!-- Text link -->
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", new_user_session_path %>
      <% end %>

    <!-- Profile picture and dropdown -->

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li> <%= link_to "Profile", edit_user_registration_path %></li>
            <li> <%= link_to "Dashboard", dashboard_attendances_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% end %>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li> <%= link_to "Profile", edit_user_registration_path %></li>
          <li> <%= link_to "Dashboard", dashboard_attendances_path %></li>
          <li><a href="#">Log Out</a></li>

        </ul>
      </div>
    </div>

  </div>
</div>

app/views/users/dashboard.html.erb
<h4>As a guest</h4>
  <% if @myevents.nil? %>
    You are not attending any event
<!--     todo : put a button to attend an event -->
<% else %>
    <% @myevents.each do |event| %>
      <h2> <%= link_to event.name, event_path(event) %> </h2>
    <% end %>
  <% end %>
<br>


<h4>as a host</h4>
  <% if @user.events.nil? %>
  <p>you re not hosting any event</p>
<!--     todo : put a button to create an event -->
  <% else %>
    <% @user.events.each do |event| %>
    <h2> <%= link_to event.name, event_path(event) %> </h2>
  <% end %>
<% end %>